version: "3.8"

volumes:
    SmartSchoolDb:

networks: 
    mysqlNET:
    smartschoolNET:

services:
    mysql:
        image: "mysql:5.7"
        container_name: mysql
        ports:
            - "3306:3306"
        volumes:
            - SmartSchoolDb:/var/lib/mysql
        networks: 
            - mysqlNET
        environment:
            - MYSQL_ROOT_PASSWORD=lalaland
            - bind-address:0.0.0.0
            - MYSQL_ROOT_HOST=%

    smartschool:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: smartschool
        ports:
            - 5000:80
        networks: 
            - mysqlNET
            - smartschoolNET
        environment:
            - DBHOST=mysql
        depends_on:
            - mysql
            
